# Generated by Django 3.1.5 on 2021-01-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Cosmetics', 'Cosmetics'), ('Mylomoika', 'Mylomoika')], max_length=200)),
                ('price', models.ImageField(upload_to='')),
            ],
        ),
    ]
