# Generated by Django 3.1.5 on 2021-01-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210120_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
