# Generated by Django 3.1.5 on 2021-01-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_product_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_file',
        ),
    ]
