# Generated by Django 3.1.5 on 2021-01-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210122_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default_product_image.jpg', null=True, upload_to=''),
        ),
    ]
