# Generated by Django 3.1.5 on 2021-02-08 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210205_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default=datetime.date(2021, 2, 8)),
        ),
    ]
